<a href="https://colab.research.google.com/github/srinidhibv1403/1BM23CS339-ML/blob/main/1BM23CS339_lab_7_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score
from sklearn.preprocessing import label_binarize, LabelEncoder

# ==========================================
# PART 1: IRIS DATASET
# ==========================================

print("========== IRIS DATASET ==========")

iris = pd.read_csv("iris.csv")

X_iris = iris.drop("species", axis=1)
y_iris = iris["species"]

X_train_i, X_test_i, y_train_i, y_test_i = train_test_split(
    X_iris, y_iris, test_size=0.2, random_state=42
)

# Linear Kernel
svm_linear = SVC(kernel='linear')
svm_linear.fit(X_train_i, y_train_i)
y_pred_linear = svm_linear.predict(X_test_i)

# RBF Kernel
svm_rbf = SVC(kernel='rbf')
svm_rbf.fit(X_train_i, y_train_i)
y_pred_rbf = svm_rbf.predict(X_test_i)

print("\n--- Linear Kernel ---")
print("Accuracy:", accuracy_score(y_test_i, y_pred_linear))
print("Confusion Matrix:\n", confusion_matrix(y_test_i, y_pred_linear))

print("\n--- RBF Kernel ---")
print("Accuracy:", accuracy_score(y_test_i, y_pred_rbf))
print("Confusion Matrix:\n", confusion_matrix(y_test_i, y_pred_rbf))


# ==========================================
# PART 2: DRUG DATASET
# ==========================================

print("\n\n========== DRUG DATASET ==========")

drug = pd.read_csv("drug.csv")

# Encode categorical columns
le = LabelEncoder()
for col in drug.columns:
    if drug[col].dtype == 'object':
        drug[col] = le.fit_transform(drug[col])

X_drug = drug.drop("Drug", axis=1)
y_drug = drug["Drug"]

X_train_d, X_test_d, y_train_d, y_test_d = train_test_split(
    X_drug, y_drug, test_size=0.2, random_state=42
)

svm_drug = SVC(kernel='rbf')
svm_drug.fit(X_train_d, y_train_d)
y_pred_d = svm_drug.predict(X_test_d)

print("Accuracy:", accuracy_score(y_test_d, y_pred_d))
print("Confusion Matrix:\n", confusion_matrix(y_test_d, y_pred_d))


# ==========================================
# PART 3: LETTER RECOGNITION DATASET
# ==========================================

print("\n\n========== LETTER RECOGNITION ==========")

letter = pd.read_csv("letter-recognition.csv")

X_letter = letter.iloc[:, 1:]
y_letter = letter.iloc[:, 0]

X_train_l, X_test_l, y_train_l, y_test_l = train_test_split(
    X_letter, y_letter, test_size=0.2, random_state=42
)

svm_letter = SVC(kernel='rbf', probability=True)
svm_letter.fit(X_train_l, y_train_l)

y_pred_l = svm_letter.predict(X_test_l)

print("\nFull Accuracy:", accuracy_score(y_test_l, y_pred_l))

# ==========================================
# REDUCED CONFUSION MATRIX (A–E ONLY)
# ==========================================

selected_labels = ['A', 'B', 'C', 'D', 'E']

mask = np.isin(y_test_l, selected_labels)

y_true_subset = y_test_l[mask]
y_pred_subset = y_pred_l[mask]

cm_subset = confusion_matrix(y_true_subset, y_pred_subset, labels=selected_labels)

print("\nReduced Confusion Matrix (A–E):\n", cm_subset)


# ==========================================
# ROC & AUC
# ==========================================

classes = sorted(y_letter.unique())

y_test_bin = label_binarize(y_test_l, classes=classes)
y_score = svm_letter.predict_proba(X_test_l)

auc = roc_auc_score(y_test_bin, y_score, multi_class='ovr')

print("\nAUC Score:", auc)


========== IRIS DATASET ==========

--- Linear Kernel ---
Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

--- RBF Kernel ---
Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


========== DRUG DATASET ==========
Accuracy: 0.625
Confusion Matrix:
 [[ 0  0  0  6  0]
 [ 0  0  0  3  0]
 [ 0  0  0  4  1]
 [ 0  0  0 10  1]
 [ 0  0  0  0 15]]


========== LETTER RECOGNITION ==========

Full Accuracy: 0.9305

Reduced Confusion Matrix (A–E):
 [[144   0   1   0   0]
 [  0 143   0   5   0]
 [  0   0 123   0   2]
 [  0   1   0 153   0]
 [  0   3   1   0 130]]

AUC Score: 0.9985064219610631
